version: "3.8"
services:
  backend:
    container_name: backend_container
    image: backend_image-v1.0.0
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - shared-network

  frontend:
    container_name: frontend_container
    image: frontend_image-v1.0.0
    restart: unless-stopped
    build:
      context: ./client/soulsbingo
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - shared-network
    depends_on:
      - backend

networks:
  shared-network:
