version: "3.8"
services:
  soulsbingo_db:
    image: postgres
    cpus: 1
    restart: always
    build:
      context: ./database
      dockerfile: Dockerfile
    hostname: bingo_db
    env_file: ./server/.env
    ports:
      - "5432:5432"
    networks:
      - shared-network
    volumes:
      - ./database/bingo_db:/var/lib/postgresql/data

  backend:
    container_name: backend_container
    image: backend_image-v1.0.0
    cpus: 1
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - shared-network
    depends_on:
      - soulsbingo_db

  frontend:
    container_name: frontend_container
    image: frontend_image-v1.0.0
    cpus: 1
    restart: unless-stopped
    build:
      context: ./client/soulsbingo
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    networks:
      - shared-network
    depends_on:
      - backend

networks:
  shared-network:
